### PR TITLE
Added and updated film pages

### PR DESCRIPTION
**Pull request by Yunnn-hahaha**

### CODE REVIEW

**Comment by Yunnn-hahaha** [comment]
According to Jan's request, we will not include teasers on the website, only the official trailer.
---
- Each film poster get its own section under the corresponding film and is therefore removed from homepage
- On homepage there should only be the latest showreel (we will do the a new one for 2024) and the latest post from the News section
- Our description can be replaced with: "We are an artistic group making short films."
(if anyone complains I am to blame)
- Every film has the list of cast and crew (copy/paste from my Vimeo trailer)
- We don't need teasers on the website, only on YT channel
---

**Comment by miha-meglic** [comment]
Jan agreed to list cast and crew in the following format:
```md
<span class="font-light">Cast:</span> Miha Rodman, Anka Eržen, Sara Horžen  
<span class="font-light">Director:</span> Jan Fabris  
<span class="font-light">Writer:</span> Sara Horžen, Jan Fabris  
<span class="font-light">Director of Photography:</span> Vida Habjanič  
<span class="font-light">Production Designer:</span> Tina Merica  
```
Note that every line has two spaces at the end to force it to make a new line.
If you're having problems with auto-formatting in VS Code, disable it.

Also in the above example, it's shown to change `Directed by:` into `Director:` and it's the same for a couple of other cases, we shouldn't use `by`.

Can you take care of the mentioned changes and then we'll merge the request.
P.S. You left the teasers in klaras-dance.mdx 😛

**Comment by Yunnn-hahaha** [comment]
Okay, will do.

**Comment by Yunnn-hahaha** [comment]
For sidebar: shall we remove the color change after clicking those icons? Also, maybe link the new Facebook page now?

**Pull request merged**
